-- Drop everything this project created — idempotent re-set
DROP PUBLICATION IF EXISTS sf_realtime_publication;
DROP FUNCTION IF EXISTS touch_updated_at() CASCADE;
DROP TRIGGER IF EXISTS trg_users_updated_at         ON users;
DROP TRIGGER IF EXISTS trg_sessions_updated_at       ON sessions;
DROP TRIGGER IF EXISTS trg_assignments_updated_at    ON assignments;
DROP TRIGGER IF EXISTS trg_modules_updated_at        ON modules;
DROP TRIGGER IF EXISTS trg_assessments_updated_at    ON assessments;
DROP POLICY IF EXISTS users_read_policy              ON users;
DROP POLICY IF EXISTS users_insert_policy            ON users;
DROP POLICY IF EXISTS users_update_policy            ON users;
DROP POLICY IF EXISTS users_delete_policy            ON users;
DROP POLICY IF EXISTS sessions_owner_read            ON sessions;
DROP POLICY IF EXISTS sessions_insert_allows         ON sessions;
DROP POLICY IF EXISTS sessions_update_allows         ON sessions;
DROP POLICY IF EXISTS sessions_delete_allows         ON sessions;
DROP POLICY IF EXISTS assignments_read_owner         ON assignments;
DROP POLICY IF EXISTS assignments_insert_allows      ON assignments;
DROP POLICY IF EXISTS assignments_update_allows      ON assignments;
DROP POLICY IF EXISTS assignments_delete_allows      ON assignments;
DROP POLICY IF EXISTS modules_read                   ON modules;
DROP POLICY IF EXISTS modules_insert_allows          ON modules;
DROP POLICY IF EXISTS modules_update_allows          ON modules;
DROP POLICY IF EXISTS modules_delete_allows          ON modules;
DROP POLICY IF EXISTS packages_read                  ON packages;
DROP POLICY IF EXISTS packages_insert_allows         ON packages;
DROP POLICY IF EXISTS packages_update_allows         ON packages;
DROP POLICY IF EXISTS packages_delete_allows         ON packages;
DROP POLICY IF EXISTS skill_packages_read            ON skill_packages;
DROP POLICY IF EXISTS skill_packages_insert_allows   ON skill_packages;
DROP POLICY IF EXISTS skill_packages_update_allows   ON skill_packages;
DROP POLICY IF EXISTS skill_packages_delete_allows   ON skill_packages;
DROP POLICY IF EXISTS learning_tracks_read           ON learning_tracks;
DROP POLICY IF EXISTS learning_tracks_insert_allows  ON learning_tracks;
DROP POLICY IF EXISTS learning_tracks_update_allows  ON learning_tracks;
DROP POLICY IF EXISTS learning_tracks_delete_allows  ON learning_tracks;
DROP POLICY IF EXISTS assessments_read               ON assessments;
DROP POLICY IF EXISTS assessments_insert_allows      ON assessments;
DROP POLICY IF EXISTS assessments_update_allows      ON assessments;
DROP POLICY IF EXISTS assessments_delete_allows      ON assessments;
DROP POLICY IF EXISTS audit_logs_insert              ON audit_logs;
DROP POLICY IF EXISTS audit_logs_read                ON audit_logs;
DROP POLICY IF EXISTS audit_logs_update              ON audit_logs;
DROP POLICY IF EXISTS audit_logs_delete              ON audit_logs;
DROP POLICY IF EXISTS groups_read                    ON groups;
DROP POLICY IF EXISTS groups_insert_allows           ON groups;
DROP POLICY IF EXISTS groups_update_allows           ON groups;
DROP POLICY IF EXISTS groups_delete_allows           ON groups;
DROP TABLE IF EXISTS users          CASCADE;
DROP TABLE IF EXISTS sessions       CASCADE;
DROP TABLE IF EXISTS assignments    CASCADE;
DROP TABLE IF EXISTS modules        CASCADE;
DROP TABLE IF EXISTS packages       CASCADE;
DROP TABLE IF EXISTS skill_packages CASCADE;
DROP TABLE IF EXISTS learning_tracks CASCADE;
DROP TABLE IF EXISTS assessments    CASCADE;
DROP TABLE IF EXISTS audit_logs     CASCADE;
DROP TABLE IF EXISTS groups         CASCADE;
